"""esquema inicial

Revision ID: 0001_esquema_inicial
Revises: 
Create Date: 2026-09-12 00:48:41.068423
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = '0001_esquema_inicial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_genericos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_canonico', sa.String(length=250), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_por', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('base_genericos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_base_genericos_nome_canonico'), ['nome_canonico'], unique=True)

    op.create_table('fs_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('PASTA', 'ARQUIVO', name='tiponode'), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statusnode'), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('origem_parent_id', sa.Integer(), nullable=True),
    sa.Column('criado_por', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['fs_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fs_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fs_nodes_parent_id'), ['parent_id'], unique=False)

    op.create_table('lojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cidade', sa.String(length=120), nullable=False),
    sa.Column('atendente_comercial', sa.String(length=120), nullable=True),
    sa.Column('consultor_farma', sa.String(length=120), nullable=True),
    sa.Column('consultor_interno', sa.String(length=120), nullable=True),
    sa.Column('grupo_economico', sa.String(length=150), nullable=True),
    sa.Column('fonte', sa.String(length=30), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lojas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lojas_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_lojas_grupo_economico'), ['grupo_economico'], unique=False)
        batch_op.create_index(batch_op.f('ix_lojas_uf'), ['uf'], unique=False)

    op.create_table('ultimos_mapeamentos_coluna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor', sa.Enum('GPS', 'GRUPPY', name='origemfila'), nullable=False),
    sa.Column('campo', sa.String(length=40), nullable=False),
    sa.Column('nome_coluna', sa.String(length=255), nullable=False),
    sa.Column('atualizado_por', sa.String(length=120), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fornecedor', 'campo', name='uq_ultimo_mapeamento_fornecedor_campo')
    )
    with op.batch_alter_table('ultimos_mapeamentos_coluna', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ultimos_mapeamentos_coluna_fornecedor'), ['fornecedor'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj_login', sa.String(length=18), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('papel', sa.Enum('ADMIN', 'CONSULTOR', name='papel'), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj_login', 'papel', name='uq_login_papel')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_cnpj_login'), ['cnpj_login'], unique=False)

    op.create_table('verificacoes_ips_streamlit_cloud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verificado_em', sa.DateTime(), nullable=False),
    sa.Column('ips_publicados_snapshot', sa.Text(), nullable=False),
    sa.Column('divergente', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ean_genericos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=40), nullable=False),
    sa.Column('base_generico_id', sa.Integer(), nullable=False),
    sa.Column('origem_resolucao', sa.Enum('AUTOMATICA', 'MANUAL', 'IMPORTADA', name='origemresolucao'), nullable=False),
    sa.Column('score_similaridade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('descricao_origem_snapshot', sa.Text(), nullable=False),
    sa.Column('resolvido_por', sa.String(length=120), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_generico_id'], ['base_genericos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ean_genericos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ean_genericos_base_generico_id'), ['base_generico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ean_genericos_ean'), ['ean'], unique=True)

    op.create_table('fila_cnpj_orfao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social_observada', sa.String(length=200), nullable=True),
    sa.Column('valor_total_acumulado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('qtd_ocorrencias', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'RESOLVIDA', 'IGNORADA', name='statusfila'), nullable=False),
    sa.Column('resolvido_para_loja_id', sa.Integer(), nullable=True),
    sa.Column('uploads_fs_node_ids_json', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolvido_para_loja_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fila_cnpj_orfao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fila_cnpj_orfao_cnpj'), ['cnpj'], unique=True)

    op.create_table('fila_resolucao_ean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=40), nullable=False),
    sa.Column('descricao_observada', sa.String(length=250), nullable=False),
    sa.Column('origem', sa.Enum('GPS', 'GRUPPY', name='origemfila'), nullable=False),
    sa.Column('sugestao_base_generico_id', sa.Integer(), nullable=True),
    sa.Column('sugestao_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valor_total_acumulado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('aparece_em_estoque', sa.Boolean(), nullable=False),
    sa.Column('qtd_ocorrencias', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'RESOLVIDA', 'IGNORADA', name='statusfila'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sugestao_base_generico_id'], ['base_genericos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fila_resolucao_ean', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fila_resolucao_ean_ean'), ['ean'], unique=True)

    op.create_table('registros_compra_gps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loja_id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=40), nullable=False),
    sa.Column('descricao_origem', sa.String(length=250), nullable=False),
    sa.Column('laboratorio_compra', sa.String(length=150), nullable=True),
    sa.Column('ano_mes', sa.String(length=7), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('fat_liquido', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('pct_cmv', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('estoque', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('upload_fs_node_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.ForeignKeyConstraint(['upload_fs_node_id'], ['fs_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loja_id', 'ean', 'ano_mes', name='uq_compra_loja_ean_mes')
    )
    with op.batch_alter_table('registros_compra_gps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_compra_gps_ano_mes'), ['ano_mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_compra_gps_ean'), ['ean'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_compra_gps_loja_id'), ['loja_id'], unique=False)

    op.create_table('tabelas_gruppy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratorio', sa.String(length=150), nullable=False),
    sa.Column('modo_custo', sa.Enum('PRONTO', 'BRUTO_DESCONTO', name='modocustogruppy'), nullable=False),
    sa.Column('nome_arquivo_origem', sa.String(length=255), nullable=False),
    sa.Column('upload_fs_node_id', sa.Integer(), nullable=True),
    sa.Column('mapa_colunas_json', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.String(length=120), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_fs_node_id'], ['fs_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tabelas_gruppy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tabelas_gruppy_laboratorio'), ['laboratorio'], unique=False)

    op.create_table('uploads_gps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fs_node_id', sa.Integer(), nullable=False),
    sa.Column('ano_mes', sa.String(length=7), nullable=False),
    sa.Column('mapa_colunas_json', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.String(length=120), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fs_node_id'], ['fs_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploads_gps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_gps_fs_node_id'), ['fs_node_id'], unique=True)

    op.create_table('itens_tabela_gruppy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabela_gruppy_id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=40), nullable=False),
    sa.Column('descricao_origem', sa.String(length=250), nullable=False),
    sa.Column('custo_liquido', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('preco_bruto', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('percentual_desconto', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tabela_gruppy_id'], ['tabelas_gruppy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_tabela_gruppy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_tabela_gruppy_ean'), ['ean'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_tabela_gruppy_tabela_gruppy_id'), ['tabela_gruppy_id'], unique=False)

    op.create_table('tabelas_gruppy_cobertura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabela_gruppy_id', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('status', sa.Enum('ATIVA', 'INATIVA', name='statuscobertura'), nullable=False),
    sa.Column('inativada_em', sa.DateTime(), nullable=True),
    sa.Column('inativada_por', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['tabela_gruppy_id'], ['tabelas_gruppy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tabelas_gruppy_cobertura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tabelas_gruppy_cobertura_tabela_gruppy_id'), ['tabela_gruppy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tabelas_gruppy_cobertura_uf'), ['uf'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabelas_gruppy_cobertura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tabelas_gruppy_cobertura_uf'))
        batch_op.drop_index(batch_op.f('ix_tabelas_gruppy_cobertura_tabela_gruppy_id'))

    op.drop_table('tabelas_gruppy_cobertura')
    with op.batch_alter_table('itens_tabela_gruppy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_tabela_gruppy_tabela_gruppy_id'))
        batch_op.drop_index(batch_op.f('ix_itens_tabela_gruppy_ean'))

    op.drop_table('itens_tabela_gruppy')
    with op.batch_alter_table('uploads_gps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_gps_fs_node_id'))

    op.drop_table('uploads_gps')
    with op.batch_alter_table('tabelas_gruppy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tabelas_gruppy_laboratorio'))

    op.drop_table('tabelas_gruppy')
    with op.batch_alter_table('registros_compra_gps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_compra_gps_loja_id'))
        batch_op.drop_index(batch_op.f('ix_registros_compra_gps_ean'))
        batch_op.drop_index(batch_op.f('ix_registros_compra_gps_ano_mes'))

    op.drop_table('registros_compra_gps')
    with op.batch_alter_table('fila_resolucao_ean', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fila_resolucao_ean_ean'))

    op.drop_table('fila_resolucao_ean')
    with op.batch_alter_table('fila_cnpj_orfao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fila_cnpj_orfao_cnpj'))

    op.drop_table('fila_cnpj_orfao')
    with op.batch_alter_table('ean_genericos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ean_genericos_ean'))
        batch_op.drop_index(batch_op.f('ix_ean_genericos_base_generico_id'))

    op.drop_table('ean_genericos')
    op.drop_table('verificacoes_ips_streamlit_cloud')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_cnpj_login'))

    op.drop_table('usuarios')
    with op.batch_alter_table('ultimos_mapeamentos_coluna', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ultimos_mapeamentos_coluna_fornecedor'))

    op.drop_table('ultimos_mapeamentos_coluna')
    with op.batch_alter_table('lojas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lojas_uf'))
        batch_op.drop_index(batch_op.f('ix_lojas_grupo_economico'))
        batch_op.drop_index(batch_op.f('ix_lojas_cnpj'))

    op.drop_table('lojas')
    with op.batch_alter_table('fs_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fs_nodes_parent_id'))

    op.drop_table('fs_nodes')
    with op.batch_alter_table('base_genericos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_base_genericos_nome_canonico'))

    op.drop_table('base_genericos')
    # ### end Alembic commands ###
